name: 'Docker build and push GCP AR'

# **Called workflow**
on:
  workflow_call:
    inputs:
      APP_NAME:
        description: "Name of the app to be built"
        required: true
        type: string
      APP_DIR:
        description: "Direcory of the app to be built"
        required: true
        type: string
      DOCKERFILE_PATH:
        description: "Path to Dockerfile"
        required: true
        type: string

# Build applications from docker images and upload to Google Artifact Registry
jobs:
  docker:
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Authenticate to Google CLoud
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SA_EMAIL }}
        token_format: 'access_token'

    - name: Docker login to GCP
      uses: docker/login-action@v2
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    # Build Docker Container image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Push Docker Container Image to Google Artifact Registry
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.APP_DIR }}
        push: true
        tags: |
          europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ARTIFACT_REPO }}/${{ inputs.APP_NAME }}:${{ github.sha }}
        file: ${{ inputs.DOCKERFILE_PATH }}
